name: ExplosionReversal
version: 5.1.0-DEV
main: net.starlegacy.explosionreversal.ExplosionReversalPlugin
authors: ["MicleBrick", "SijmenSchoon", "rsammelson", "trainb0y1"]
api-version: "1.18"
commands:
  regen:
    permission: explosionreversal.regen
  explosionreversalreload:
    permission: explosionreversal.reload
